import React, { useState } from "react";
import { jsPDF } from "jspdf"; // Ensure jsPDF is installed

export default function ResumeScoreChecker() {
  const [resumeFile, setResumeFile] = useState(null);
  const [atsScore, setAtsScore] = useState(null);
  const [message, setMessage] = useState("");
  const [tips, setTips] = useState([]);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [isUploading, setIsUploading] = useState(false);

  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (file) {
      setResumeFile(file);
      simulateUpload(file);
    }
  };

  const simulateUpload = (file) => {
    setIsUploading(true);
    setUploadProgress(0);

    const interval = setInterval(() => {
      setUploadProgress((prev) => {
        if (prev >= 100) {
          clearInterval(interval);
          setIsUploading(false);
          calculateATSScore(file);
          return 100;
        }
        return prev + 10;
      });
    }, 200);
  };

  const calculateATSScore = (file) => {
    let score = 0;
    const tipsArray = [];

    const fileType = file.name.split(".").pop().toLowerCase();
    if (fileType === "pdf") score += 20;
    else if (fileType === "docx" || fileType === "doc") {
      score += 15;
      tipsArray.push("Convert your resume to PDF for optimal ATS compatibility.");
    } else {
      tipsArray.push("Use PDF format; other formats may not parse correctly in ATS systems.");
    }

    const fileName = file.name.toLowerCase();
    const hasKeywords = /(resume|cv|john|jane|doe|202[0-5])/i.test(fileName);
    if (hasKeywords && !fileName.includes(" ")) score += 30;
    else if (hasKeywords) {
      score += 20;
      tipsArray.push("Remove spaces from the file name (e.g., 'JohnDoeResume.pdf').");
    } else {
      score += 10;
      tipsArray.push("Include your name and 'resume' in the file name (e.g., 'JohnDoeResume.pdf').");
    }

    const fileSizeKB = file.size / 1024;
    if (fileSizeKB > 50 && fileSizeKB < 200) score += 30;
    else if (fileSizeKB >= 200 && fileSizeKB < 500) {
      score += 20;
      tipsArray.push("Shorten your resume to 1-2 pages for better ATS readability.");
    } else if (fileSizeKB <= 50) {
      score += 15;
      tipsArray.push("Add more relevant details; your resume might be too short.");
    } else {
      score += 10;
      tipsArray.push("Reduce resume length; ATS prefers concise documents.");
    }

    const hashScore = generateDeterministicScore(file);
    score += Math.floor((hashScore / 100) * 20);

    setAtsScore(score);
    setMessage(
      score > 85
        ? "Highly ATS-friendly resume! Ready for job applications."
        : score > 70
        ? "Good ATS compatibility! Minor adjustments could improve it."
        : "Your resume needs work to optimize for ATS systems."
    );
    setTips(tipsArray.length > 0 ? tipsArray : ["Your resume is already well-optimized for ATS!"]);
  };

  const generateDeterministicScore = (file) => {
    const input = file.name + file.size;
    let hash = 0;
    for (let i = 0; i < input.length; i++) {
      const char = input.charCodeAt(i);
      hash = (hash << 5) - hash + char;
      hash = hash & hash;
    }
    return 60 + Math.abs(hash) % 41;
  };

  const downloadReport = () => {
    if (!resumeFile || atsScore === null) return;

    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(33, 150, 243);
    doc.text("ATS Resume Analysis Report", 20, 20);
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`File Name: ${resumeFile.name}`, 20, 40);
    doc.text(`File Size: ${(resumeFile.size / 1024).toFixed(2)} KB`, 20, 50);
    doc.setFontSize(16);
    doc.setTextColor(33, 150, 243);
    doc.text(`ATS Score: ${atsScore} / 100`, 20, 70);
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Feedback: ${message}`, 20, 80, { maxWidth: 170 });
    doc.setFontSize(14);
    doc.setTextColor(33, 150, 243);
    doc.text("Recommended Improvements:", 20, 100);
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    tips.forEach((tip, index) => {
      doc.text(`- ${tip}`, 25, 110 + index * 10, { maxWidth: 160 });
    });
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by ATS Resume Analyzer", 20, doc.internal.pageSize.height - 10);

    doc.save(`${resumeFile.name}_ATS_Report.pdf`);
  };

  return (
    <div className="bg-gradient-to-br from-gray-50 to-gray-100 min-h-screen flex flex-col items-center py-20">
      <div className="max-w-2xl w-full px-6">
        <h1 className="text-4xl font-extrabold text-gray-900 mb-4 text-center">
          ATS Resume Analyzer
        </h1>
        <p className="text-lg text-gray-600 text-center mb-12">
          Upload your resume to evaluate its ATS compatibility and get a detailed report.
        </p>

        <div className="bg-white rounded-xl shadow-lg p-8 transition-all duration-300 hover:shadow-xl">
          <input
            type="file"
            accept=".pdf,.doc,.docx"
            onChange={handleFileUpload}
            className="block w-full text-sm text-gray-600 file:mr-4 file:py-3 file:px-6 file:rounded-lg file:border-0 file:text-sm file:font-medium file:bg-indigo-600 file:text-white hover:file:bg-indigo-700 cursor-pointer"
          />

          {isUploading && (
            <div className="mt-6">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm text-gray-600">Uploading...</span>
                <span className="text-sm text-indigo-600">{uploadProgress}%</span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-2.5">
                <div
                  className="bg-indigo-600 h-2.5 rounded-full transition-all duration-300"
                  style={{ width: `${uploadProgress}%` }}
                ></div>
              </div>
            </div>
          )}

          {resumeFile && !isUploading && (
            <div className="mt-6 bg-gray-50 p-4 rounded-lg">
              <p className="text-gray-700 text-sm">
                <span className="font-medium">Selected File:</span> {resumeFile.name}
              </p>
            </div>
          )}

          {atsScore !== null && !isUploading && (
            <div className="mt-8 border-t pt-6">
              <h3 className="text-2xl font-semibold text-gray-900">
                Your ATS Score:{" "}
                <span
                  className={`${
                    atsScore > 85 ? "text-green-600" : atsScore > 70 ? "text-blue-600" : "text-red-600"
                  }`}
                >
                  {atsScore} / 100
                </span>
              </h3>
              <p className="text-gray-600 mt-3 text-base">{message}</p>
              <div className="mt-4">
                <div className="w-full bg-gray-200 rounded-full h-3">
                  <div
                    className={`h-3 rounded-full transition-all duration-500 ${
                      atsScore > 85 ? "bg-green-500" : atsScore > 70 ? "bg-blue-500" : "bg-red-500"
                    }`}
                    style={{ width: `${atsScore}%` }}
                  ></div>
                </div>
              </div>
              <div className="mt-6">
                <h4 className="text-lg font-medium text-gray-800">Improvement Tips:</h4>
                <ul className="list-disc pl-5 mt-2 text-gray-600 text-sm">
                  {tips.map((tip, index) => (
                    <li key={index}>{tip}</li>
                  ))}
                </ul>
              </div>
            </div>
          )}
        </div>

        {atsScore !== null && !isUploading && (
          <div className="mt-8 text-center">
            <button
              onClick={downloadReport}
              className="px-6 py-2 bg-indigo-600 text-white rounded-lg font-medium hover:bg-indigo-700 transition-colors duration-200"
            >
              Download ATS Report
            </button>
          </div>
        )}
      </div>
    </div>
  );
}